name: neural_style_transfer
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3
  - numpy 
  - scipy
  - matplotlib
  - scikit-learn
  - jupyter
  - pytorch
  - torchvision
  - cpuonly
  - pillow
